services:
  frontend:
    networks:
      - traefik-public
      - mariadb-network
      - bench-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${ROUTER?ROUTER not set}.loadbalancer.server.port=8080
      - traefik.http.routers.${ROUTER}-http.service=${ROUTER}
      - traefik.http.routers.${ROUTER}-http.entrypoints=http
      - traefik.http.routers.${ROUTER}-http.rule=Host(${SITES?SITES not set})
  configurator:
    networks:
      - mariadb-network
  backend:
    networks:
      - mariadb-network
  websocket:
    networks:
      - mariadb-network
  scheduler:
    networks:
      - mariadb-network
  queue-default:
    networks:
      - mariadb-network
  queue-short:
    networks:
      - mariadb-network
  queue-long:
    networks:
      - mariadb-network
  redis:
    networks:
      - mariadb-network

networks:
  traefik-public:
    external: true
  mariadb-network:
    external: true
  bench-network:
    name: ${ROUTER}
    external: false
